### ISSUE TITLE
Create Question Class

### ISSUE THREAD

**Issue by Nolski** [chrisknepper/Fractionauts#19]
Create a class that would act as a question in the game. This will include:
A way to generate a question (probably using random)
A way to generate possible options for answer vials (make sure that at least some of these will work for the answer)
Add anything else that might seem useful

**Comment by LanceALaughlin** [comment]
Question class is created now and generates a random fraction (their goal fraction)

**Comment by LanceALaughlin** [comment]
Question class is implemented for addition - will add other add other operations when first level is completed.
